pipeline {
    agent any
    tools {
        maven 'maven3' //This should be defined in Global Tool Configuration maven installatons with name "maven3"
    }
	parameters {
		string(name: 'DOCKER_REPO_ID', defaultValue: 'gopinathg01', description: 'Docker ID belong to the dockerhub repository')
		booleanParam(name: 'IS_CD_DIR', defaultValue: 'true', description: 'If changing to a directory required')
	}
	environment {
		//Create a Jenkins credential with the name dockerhub, save your username/password.
		DOCKER_CREDS = credentials('docker-cred')
	}
    stages {		
        stage('Test') {
            steps {
				script {
					if (params.IS_CD_DIR) {
						dir('file-upload-multiple-options') {
							sh 'mvn clean test' 
						}
					} else {
						sh 'mvn clean test'
					}
				}
            }
        }
		stage('Build') {
            steps {
				script {
					if (params.IS_CD_DIR) {
						dir('file-upload-multiple-options') {
							sh 'mvn clean package' 
						}
					} else {
						sh 'mvn clean package'
					}
				}
            }
        }
        stage('create docker image') {
			steps {
				script {
					if (params.IS_CD_DIR) {
						dir('file-upload-multiple-options') {
							sh 'docker login --username $DOCKER_CREDS_USR --password $DOCKER_CREDS_PSW'
							sh ("docker build -t ${params.DOCKER_REPO_ID}/file-upload-multiple-options:latest .")
						}
					} else {
						sh 'docker login --username $DOCKER_CREDS_USR --password $DOCKER_CREDS_PSW'
						sh ("docker build -t ${params.DOCKER_REPO_ID}/file-upload-multiple-options:latest .")
					}
				}
			}
		}
		stage('push docker image') {
			steps {
				sh ("docker push  ${params.DOCKER_REPO_ID}/file-upload-multiple-options:latest")
			}
        }
		stage('Run Application') {
			steps {
				sh 'docker login --username $DOCKER_CREDS_USR --password $DOCKER_CREDS_PSW'
				sh ("docker run -dp 9000:9000 ${params.DOCKER_REPO_ID}/file-upload-multiple-options:latest --server.port=9000")
			}
		}
    }
}
